//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5444
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsCompany 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsCompany : Entity 
	{
		public cmsCompany():base("cmsCompany") {}

		#region Model
		private long _Id;
		private string _ComName;
		private string _ComAddr;
		private string _ComZipcode;
		private string _ComTel;
		private string _ComFax;
		private string _ComEmail;
		private string _ComUrl;
		private string _Summary;
		private long? _LangId;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ComName
		{
			get{ return _ComName; }
			set
			{
				this.OnPropertyValueChange(_.ComName,_ComName,value);
				this._ComName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ComAddr
		{
			get{ return _ComAddr; }
			set
			{
				this.OnPropertyValueChange(_.ComAddr,_ComAddr,value);
				this._ComAddr=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ComZipcode
		{
			get{ return _ComZipcode; }
			set
			{
				this.OnPropertyValueChange(_.ComZipcode,_ComZipcode,value);
				this._ComZipcode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ComTel
		{
			get{ return _ComTel; }
			set
			{
				this.OnPropertyValueChange(_.ComTel,_ComTel,value);
				this._ComTel=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ComFax
		{
			get{ return _ComFax; }
			set
			{
				this.OnPropertyValueChange(_.ComFax,_ComFax,value);
				this._ComFax=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ComEmail
		{
			get{ return _ComEmail; }
			set
			{
				this.OnPropertyValueChange(_.ComEmail,_ComEmail,value);
				this._ComEmail=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ComUrl
		{
			get{ return _ComUrl; }
			set
			{
				this.OnPropertyValueChange(_.ComUrl,_ComUrl,value);
				this._ComUrl=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Summary
		{
			get{ return _Summary; }
			set
			{
				this.OnPropertyValueChange(_.Summary,_Summary,value);
				this._Summary=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long? LangId
		{
			get{ return _LangId; }
			set
			{
				this.OnPropertyValueChange(_.LangId,_LangId,value);
				this._LangId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ComName,
				_.ComAddr,
				_.ComZipcode,
				_.ComTel,
				_.ComFax,
				_.ComEmail,
				_.ComUrl,
				_.Summary,
				_.LangId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ComName,
				this._ComAddr,
				this._ComZipcode,
				this._ComTel,
				this._ComFax,
				this._ComEmail,
				this._ComUrl,
				this._Summary,
				this._LangId};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._ComName = DataUtils.ConvertValue<string>(reader["ComName"]);
			this._ComAddr = DataUtils.ConvertValue<string>(reader["ComAddr"]);
			this._ComZipcode = DataUtils.ConvertValue<string>(reader["ComZipcode"]);
			this._ComTel = DataUtils.ConvertValue<string>(reader["ComTel"]);
			this._ComFax = DataUtils.ConvertValue<string>(reader["ComFax"]);
			this._ComEmail = DataUtils.ConvertValue<string>(reader["ComEmail"]);
			this._ComUrl = DataUtils.ConvertValue<string>(reader["ComUrl"]);
			this._Summary = DataUtils.ConvertValue<string>(reader["Summary"]);
			this._LangId = DataUtils.ConvertValue<long?>(reader["LangId"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._ComName = DataUtils.ConvertValue<string>(row["ComName"]);
			this._ComAddr = DataUtils.ConvertValue<string>(row["ComAddr"]);
			this._ComZipcode = DataUtils.ConvertValue<string>(row["ComZipcode"]);
			this._ComTel = DataUtils.ConvertValue<string>(row["ComTel"]);
			this._ComFax = DataUtils.ConvertValue<string>(row["ComFax"]);
			this._ComEmail = DataUtils.ConvertValue<string>(row["ComEmail"]);
			this._ComUrl = DataUtils.ConvertValue<string>(row["ComUrl"]);
			this._Summary = DataUtils.ConvertValue<string>(row["Summary"]);
			this._LangId = DataUtils.ConvertValue<long?>(row["LangId"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsCompany");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsCompany","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ComName = new Field("ComName","cmsCompany","ComName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ComAddr = new Field("ComAddr","cmsCompany","ComAddr");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ComZipcode = new Field("ComZipcode","cmsCompany","ComZipcode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ComTel = new Field("ComTel","cmsCompany","ComTel");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ComFax = new Field("ComFax","cmsCompany","ComFax");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ComEmail = new Field("ComEmail","cmsCompany","ComEmail");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ComUrl = new Field("ComUrl","cmsCompany","ComUrl");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Summary = new Field("Summary","cmsCompany","Summary");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LangId = new Field("LangId","cmsCompany","LangId");
		}
		#endregion


	}
}

