//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5444
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsFeedback 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsFeedback : Entity 
	{
		public cmsFeedback():base("cmsFeedback") {}

		#region Model
		private long _Id;
		private string _Title;
		private string _Content;
		private string _Name;
		private string _Email;
		private string _Company;
		private string _Address;
		private string _Phone;
		private string _Fax;
		private DateTime? _PostTime;
		private int? _IsReplied;
		private long? _ReplyUser;
		private string _ReplyContent;
		private DateTime? _ReplyTime;
        private long? _ProductId;
		private long _LangId;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Email
		{
			get{ return _Email; }
			set
			{
				this.OnPropertyValueChange(_.Email,_Email,value);
				this._Email=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Company
		{
			get{ return _Company; }
			set
			{
				this.OnPropertyValueChange(_.Company,_Company,value);
				this._Company=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Address
		{
			get{ return _Address; }
			set
			{
				this.OnPropertyValueChange(_.Address,_Address,value);
				this._Address=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Phone
		{
			get{ return _Phone; }
			set
			{
				this.OnPropertyValueChange(_.Phone,_Phone,value);
				this._Phone=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Fax
		{
			get{ return _Fax; }
			set
			{
				this.OnPropertyValueChange(_.Fax,_Fax,value);
				this._Fax=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? PostTime
		{
			get{ return _PostTime; }
			set
			{
				this.OnPropertyValueChange(_.PostTime,_PostTime,value);
				this._PostTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? IsReplied
		{
			get{ return _IsReplied; }
			set
			{
				this.OnPropertyValueChange(_.IsReplied,_IsReplied,value);
				this._IsReplied=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long? ReplyUser
		{
			get{ return _ReplyUser; }
			set
			{
				this.OnPropertyValueChange(_.ReplyUser,_ReplyUser,value);
				this._ReplyUser=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ReplyContent
		{
			get{ return _ReplyContent; }
			set
			{
				this.OnPropertyValueChange(_.ReplyContent,_ReplyContent,value);
				this._ReplyContent=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ReplyTime
		{
			get{ return _ReplyTime; }
			set
			{
				this.OnPropertyValueChange(_.ReplyTime,_ReplyTime,value);
				this._ReplyTime=value;
			}
		}
        /// <summary>
        /// 
        /// </summary>
        public long? ProductId
        {
            get { return _ProductId; }
            set
            {
                this.OnPropertyValueChange(_.ProductId, _ProductId, value);
                this._ProductId = value;
            }
        }
		/// <summary>
		/// 
		/// </summary>
		public long LangId
		{
			get{ return _LangId; }
			set
			{
				this.OnPropertyValueChange(_.LangId,_LangId,value);
				this._LangId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Title,
				_.Content,
				_.Name,
				_.Email,
				_.Company,
				_.Address,
				_.Phone,
				_.Fax,
				_.PostTime,
				_.IsReplied,
				_.ReplyUser,
				_.ReplyContent,
				_.ReplyTime,
                _.ProductId,
				_.LangId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Title,
				this._Content,
				this._Name,
				this._Email,
				this._Company,
				this._Address,
				this._Phone,
				this._Fax,
				this._PostTime,
				this._IsReplied,
				this._ReplyUser,
				this._ReplyContent,
				this._ReplyTime,
                this._ProductId,
				this._LangId};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._Title = DataUtils.ConvertValue<string>(reader["Title"]);
			this._Content = DataUtils.ConvertValue<string>(reader["Content"]);
			this._Name = DataUtils.ConvertValue<string>(reader["Name"]);
			this._Email = DataUtils.ConvertValue<string>(reader["Email"]);
			this._Company = DataUtils.ConvertValue<string>(reader["Company"]);
			this._Address = DataUtils.ConvertValue<string>(reader["Address"]);
			this._Phone = DataUtils.ConvertValue<string>(reader["Phone"]);
			this._Fax = DataUtils.ConvertValue<string>(reader["Fax"]);
			this._PostTime = DataUtils.ConvertValue<DateTime?>(reader["PostTime"]);
			this._IsReplied = DataUtils.ConvertValue<int?>(reader["IsReplied"]);
			this._ReplyUser = DataUtils.ConvertValue<long?>(reader["ReplyUser"]);
			this._ReplyContent = DataUtils.ConvertValue<string>(reader["ReplyContent"]);
            this._ReplyTime = DataUtils.ConvertValue<DateTime?>(reader["ReplyTime"]);
            this._ProductId = DataUtils.ConvertValue<long?>(reader["ProductId"]);
			this._LangId = DataUtils.ConvertValue<long>(reader["LangId"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._Title = DataUtils.ConvertValue<string>(row["Title"]);
			this._Content = DataUtils.ConvertValue<string>(row["Content"]);
			this._Name = DataUtils.ConvertValue<string>(row["Name"]);
			this._Email = DataUtils.ConvertValue<string>(row["Email"]);
			this._Company = DataUtils.ConvertValue<string>(row["Company"]);
			this._Address = DataUtils.ConvertValue<string>(row["Address"]);
			this._Phone = DataUtils.ConvertValue<string>(row["Phone"]);
			this._Fax = DataUtils.ConvertValue<string>(row["Fax"]);
			this._PostTime = DataUtils.ConvertValue<DateTime?>(row["PostTime"]);
			this._IsReplied = DataUtils.ConvertValue<int?>(row["IsReplied"]);
			this._ReplyUser = DataUtils.ConvertValue<long?>(row["ReplyUser"]);
			this._ReplyContent = DataUtils.ConvertValue<string>(row["ReplyContent"]);
            this._ReplyTime = DataUtils.ConvertValue<DateTime?>(row["ReplyTime"]);
            this._ProductId = DataUtils.ConvertValue<long?>(row["ProductId"]);
			this._LangId = DataUtils.ConvertValue<long>(row["LangId"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsFeedback");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsFeedback","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","cmsFeedback","Title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Content = new Field("Content","cmsFeedback","Content");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","cmsFeedback","Name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Email = new Field("Email","cmsFeedback","Email");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Company = new Field("Company","cmsFeedback","Company");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Address = new Field("Address","cmsFeedback","Address");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Phone = new Field("Phone","cmsFeedback","Phone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Fax = new Field("Fax","cmsFeedback","Fax");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PostTime = new Field("PostTime","cmsFeedback","PostTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsReplied = new Field("IsReplied","cmsFeedback","IsReplied");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReplyUser = new Field("ReplyUser","cmsFeedback","ReplyUser");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReplyContent = new Field("ReplyContent","cmsFeedback","ReplyContent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReplyTime = new Field("ReplyTime","cmsFeedback","ReplyTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ProductId = new Field("ProductId", "cmsFeedback", "ProductId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LangId = new Field("LangId","cmsFeedback","LangId");
		}
		#endregion


	}
}

