//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3634
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsJob 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsJob : Entity 
	{
		public cmsJob():base("cmsJob") {}

		#region Model
		private long _Id;
		private string _NodeCode;
		private string _Name;
		private int? _Numbers;
		private string _Address;
		private string _Responsibilities;
		private string _Requirements;
		private string _Remark;
		private int _OrderNo;
		private int _IsEnabled;
		private int _Hits;
		private DateTime _AddTime;
		private DateTime? _EndTime;
		private long _LangId;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string NodeCode
		{
			get{ return _NodeCode; }
			set
			{
				this.OnPropertyValueChange(_.NodeCode,_NodeCode,value);
				this._NodeCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Numbers
		{
			get{ return _Numbers; }
			set
			{
				this.OnPropertyValueChange(_.Numbers,_Numbers,value);
				this._Numbers=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Address
		{
			get{ return _Address; }
			set
			{
				this.OnPropertyValueChange(_.Address,_Address,value);
				this._Address=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Responsibilities
		{
			get{ return _Responsibilities; }
			set
			{
				this.OnPropertyValueChange(_.Responsibilities,_Responsibilities,value);
				this._Responsibilities=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Requirements
		{
			get{ return _Requirements; }
			set
			{
				this.OnPropertyValueChange(_.Requirements,_Requirements,value);
				this._Requirements=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int OrderNo
		{
			get{ return _OrderNo; }
			set
			{
				this.OnPropertyValueChange(_.OrderNo,_OrderNo,value);
				this._OrderNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int IsEnabled
		{
			get{ return _IsEnabled; }
			set
			{
				this.OnPropertyValueChange(_.IsEnabled,_IsEnabled,value);
				this._IsEnabled=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int Hits
		{
			get{ return _Hits; }
			set
			{
				this.OnPropertyValueChange(_.Hits,_Hits,value);
				this._Hits=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime AddTime
		{
			get{ return _AddTime; }
			set
			{
				this.OnPropertyValueChange(_.AddTime,_AddTime,value);
				this._AddTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? EndTime
		{
			get{ return _EndTime; }
			set
			{
				this.OnPropertyValueChange(_.EndTime,_EndTime,value);
				this._EndTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long LangId
		{
			get{ return _LangId; }
			set
			{
				this.OnPropertyValueChange(_.LangId,_LangId,value);
				this._LangId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.NodeCode,
				_.Name,
				_.Numbers,
				_.Address,
				_.Responsibilities,
				_.Requirements,
				_.Remark,
				_.OrderNo,
				_.IsEnabled,
				_.Hits,
				_.AddTime,
				_.EndTime,
				_.LangId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._NodeCode,
				this._Name,
				this._Numbers,
				this._Address,
				this._Responsibilities,
				this._Requirements,
				this._Remark,
				this._OrderNo,
				this._IsEnabled,
				this._Hits,
				this._AddTime,
				this._EndTime,
				this._LangId};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._NodeCode = DataUtils.ConvertValue<string>(reader["NodeCode"]);
			this._Name = DataUtils.ConvertValue<string>(reader["Name"]);
			this._Numbers = DataUtils.ConvertValue<int?>(reader["Numbers"]);
			this._Address = DataUtils.ConvertValue<string>(reader["Address"]);
			this._Responsibilities = DataUtils.ConvertValue<string>(reader["Responsibilities"]);
			this._Requirements = DataUtils.ConvertValue<string>(reader["Requirements"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
			this._OrderNo = DataUtils.ConvertValue<int>(reader["OrderNo"]);
			this._IsEnabled = DataUtils.ConvertValue<int>(reader["IsEnabled"]);
			this._Hits = DataUtils.ConvertValue<int>(reader["Hits"]);
			this._AddTime = DataUtils.ConvertValue<DateTime>(reader["AddTime"]);
			this._EndTime = DataUtils.ConvertValue<DateTime?>(reader["EndTime"]);
			this._LangId = DataUtils.ConvertValue<long>(reader["LangId"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._NodeCode = DataUtils.ConvertValue<string>(row["NodeCode"]);
			this._Name = DataUtils.ConvertValue<string>(row["Name"]);
			this._Numbers = DataUtils.ConvertValue<int?>(row["Numbers"]);
			this._Address = DataUtils.ConvertValue<string>(row["Address"]);
			this._Responsibilities = DataUtils.ConvertValue<string>(row["Responsibilities"]);
			this._Requirements = DataUtils.ConvertValue<string>(row["Requirements"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
			this._OrderNo = DataUtils.ConvertValue<int>(row["OrderNo"]);
			this._IsEnabled = DataUtils.ConvertValue<int>(row["IsEnabled"]);
			this._Hits = DataUtils.ConvertValue<int>(row["Hits"]);
			this._AddTime = DataUtils.ConvertValue<DateTime>(row["AddTime"]);
			this._EndTime = DataUtils.ConvertValue<DateTime?>(row["EndTime"]);
			this._LangId = DataUtils.ConvertValue<long>(row["LangId"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsJob");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsJob","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NodeCode = new Field("NodeCode","cmsJob","NodeCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","cmsJob","Name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Numbers = new Field("Numbers","cmsJob","Numbers");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Address = new Field("Address","cmsJob","Address");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Responsibilities = new Field("Responsibilities","cmsJob","Responsibilities");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Requirements = new Field("Requirements","cmsJob","Requirements");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark","cmsJob","Remark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderNo = new Field("OrderNo","cmsJob","OrderNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsEnabled = new Field("IsEnabled","cmsJob","IsEnabled");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Hits = new Field("Hits","cmsJob","Hits");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime","cmsJob","AddTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EndTime = new Field("EndTime","cmsJob","EndTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LangId = new Field("LangId","cmsJob","LangId");
		}
		#endregion


	}
}

