//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5444
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsLanguage 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsLanguage : Entity 
	{
		public cmsLanguage():base("cmsLanguage") {}

		#region Model
		private long _Id;
		private string _Name;
		private string _ShortName;
        private string _Code;
		private string _HomeUrl;
		private string _Logo;
		private int? _IsEnabled;
		private int? _IsDefault;
		private int? _OrderNo;
		private string _Remark;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ShortName
		{
			get{ return _ShortName; }
			set
			{
				this.OnPropertyValueChange(_.ShortName,_ShortName,value);
				this._ShortName=value;
			}
		}
        /// <summary>
        /// 
        /// </summary>
        public string Code
        {
            get { return _Code; }
            set
            {
                this.OnPropertyValueChange(_.Code, _Code, value);
                this._Code = value;
            }
        }
		/// <summary>
		/// 
		/// </summary>
		public string HomeUrl
		{
			get{ return _HomeUrl; }
			set
			{
				this.OnPropertyValueChange(_.HomeUrl,_HomeUrl,value);
				this._HomeUrl=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Logo
		{
			get{ return _Logo; }
			set
			{
				this.OnPropertyValueChange(_.Logo,_Logo,value);
				this._Logo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? IsEnabled
		{
			get{ return _IsEnabled; }
			set
			{
				this.OnPropertyValueChange(_.IsEnabled,_IsEnabled,value);
				this._IsEnabled=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? IsDefault
		{
			get{ return _IsDefault; }
			set
			{
				this.OnPropertyValueChange(_.IsDefault,_IsDefault,value);
				this._IsDefault=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? OrderNo
		{
			get{ return _OrderNo; }
			set
			{
				this.OnPropertyValueChange(_.OrderNo,_OrderNo,value);
				this._OrderNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Name,
				_.ShortName,
                _.Code,
				_.HomeUrl,
				_.Logo,
				_.IsEnabled,
				_.IsDefault,
				_.OrderNo,
				_.Remark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Name,
				this._ShortName,
                this._Code,
				this._HomeUrl,
				this._Logo,
				this._IsEnabled,
				this._IsDefault,
				this._OrderNo,
				this._Remark};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._Name = DataUtils.ConvertValue<string>(reader["Name"]);
            this._ShortName = DataUtils.ConvertValue<string>(reader["ShortName"]);
            this._Code = DataUtils.ConvertValue<string>(reader["Code"]);
			this._HomeUrl = DataUtils.ConvertValue<string>(reader["HomeUrl"]);
			this._Logo = DataUtils.ConvertValue<string>(reader["Logo"]);
			this._IsEnabled = DataUtils.ConvertValue<int?>(reader["IsEnabled"]);
			this._IsDefault = DataUtils.ConvertValue<int?>(reader["IsDefault"]);
			this._OrderNo = DataUtils.ConvertValue<int?>(reader["OrderNo"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._Name = DataUtils.ConvertValue<string>(row["Name"]);
            this._ShortName = DataUtils.ConvertValue<string>(row["ShortName"]);
            this._Code = DataUtils.ConvertValue<string>(row["Code"]);
			this._HomeUrl = DataUtils.ConvertValue<string>(row["HomeUrl"]);
			this._Logo = DataUtils.ConvertValue<string>(row["Logo"]);
			this._IsEnabled = DataUtils.ConvertValue<int?>(row["IsEnabled"]);
			this._IsDefault = DataUtils.ConvertValue<int?>(row["IsDefault"]);
			this._OrderNo = DataUtils.ConvertValue<int?>(row["OrderNo"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsLanguage");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsLanguage","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","cmsLanguage","Name");
			/// <summary>
			/// 
			/// </summary>
            public readonly static Field ShortName = new Field("ShortName", "cmsLanguage", "ShortName");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Code = new Field("Code", "cmsLanguage", "Code");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field HomeUrl = new Field("HomeUrl","cmsLanguage","HomeUrl");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Logo = new Field("Logo","cmsLanguage","Logo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsEnabled = new Field("IsEnabled","cmsLanguage","IsEnabled");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsDefault = new Field("IsDefault","cmsLanguage","IsDefault");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderNo = new Field("OrderNo","cmsLanguage","OrderNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark","cmsLanguage","Remark");
		}
		#endregion


	}
}

