//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5444
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsMessage 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsMessage : Entity 
	{
		public cmsMessage():base("cmsMessage") {}

		#region Model
		private long _Id;
		private string _Name;
		private string _Telephone;
		private string _Email;
		private string _Content;
		private string _OtherInfo;
		private string _MsgIP;
		private int? _AddUser;
		private DateTime? _AddTime;
		private int? _IsReply;
		private string _ReplyContent;
		private int? _ReplyUser;
		private DateTime? _ReplyTime;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Telephone
		{
			get{ return _Telephone; }
			set
			{
				this.OnPropertyValueChange(_.Telephone,_Telephone,value);
				this._Telephone=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Email
		{
			get{ return _Email; }
			set
			{
				this.OnPropertyValueChange(_.Email,_Email,value);
				this._Email=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string OtherInfo
		{
			get{ return _OtherInfo; }
			set
			{
				this.OnPropertyValueChange(_.OtherInfo,_OtherInfo,value);
				this._OtherInfo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MsgIP
		{
			get{ return _MsgIP; }
			set
			{
				this.OnPropertyValueChange(_.MsgIP,_MsgIP,value);
				this._MsgIP=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? AddUser
		{
			get{ return _AddUser; }
			set
			{
				this.OnPropertyValueChange(_.AddUser,_AddUser,value);
				this._AddUser=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AddTime
		{
			get{ return _AddTime; }
			set
			{
				this.OnPropertyValueChange(_.AddTime,_AddTime,value);
				this._AddTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? IsReply
		{
			get{ return _IsReply; }
			set
			{
				this.OnPropertyValueChange(_.IsReply,_IsReply,value);
				this._IsReply=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ReplyContent
		{
			get{ return _ReplyContent; }
			set
			{
				this.OnPropertyValueChange(_.ReplyContent,_ReplyContent,value);
				this._ReplyContent=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ReplyUser
		{
			get{ return _ReplyUser; }
			set
			{
				this.OnPropertyValueChange(_.ReplyUser,_ReplyUser,value);
				this._ReplyUser=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ReplyTime
		{
			get{ return _ReplyTime; }
			set
			{
				this.OnPropertyValueChange(_.ReplyTime,_ReplyTime,value);
				this._ReplyTime=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Name,
				_.Telephone,
				_.Email,
				_.Content,
				_.OtherInfo,
				_.MsgIP,
				_.AddUser,
				_.AddTime,
				_.IsReply,
				_.ReplyContent,
				_.ReplyUser,
				_.ReplyTime};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Name,
				this._Telephone,
				this._Email,
				this._Content,
				this._OtherInfo,
				this._MsgIP,
				this._AddUser,
				this._AddTime,
				this._IsReply,
				this._ReplyContent,
				this._ReplyUser,
				this._ReplyTime};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._Name = DataUtils.ConvertValue<string>(reader["Name"]);
			this._Telephone = DataUtils.ConvertValue<string>(reader["Telephone"]);
			this._Email = DataUtils.ConvertValue<string>(reader["Email"]);
			this._Content = DataUtils.ConvertValue<string>(reader["Content"]);
			this._OtherInfo = DataUtils.ConvertValue<string>(reader["OtherInfo"]);
			this._MsgIP = DataUtils.ConvertValue<string>(reader["MsgIP"]);
			this._AddUser = DataUtils.ConvertValue<int?>(reader["AddUser"]);
			this._AddTime = DataUtils.ConvertValue<DateTime?>(reader["AddTime"]);
			this._IsReply = DataUtils.ConvertValue<int?>(reader["IsReply"]);
			this._ReplyContent = DataUtils.ConvertValue<string>(reader["ReplyContent"]);
			this._ReplyUser = DataUtils.ConvertValue<int?>(reader["ReplyUser"]);
			this._ReplyTime = DataUtils.ConvertValue<DateTime?>(reader["ReplyTime"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._Name = DataUtils.ConvertValue<string>(row["Name"]);
			this._Telephone = DataUtils.ConvertValue<string>(row["Telephone"]);
			this._Email = DataUtils.ConvertValue<string>(row["Email"]);
			this._Content = DataUtils.ConvertValue<string>(row["Content"]);
			this._OtherInfo = DataUtils.ConvertValue<string>(row["OtherInfo"]);
			this._MsgIP = DataUtils.ConvertValue<string>(row["MsgIP"]);
			this._AddUser = DataUtils.ConvertValue<int?>(row["AddUser"]);
			this._AddTime = DataUtils.ConvertValue<DateTime?>(row["AddTime"]);
			this._IsReply = DataUtils.ConvertValue<int?>(row["IsReply"]);
			this._ReplyContent = DataUtils.ConvertValue<string>(row["ReplyContent"]);
			this._ReplyUser = DataUtils.ConvertValue<int?>(row["ReplyUser"]);
			this._ReplyTime = DataUtils.ConvertValue<DateTime?>(row["ReplyTime"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsMessage");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsMessage","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","cmsMessage","Name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Telephone = new Field("Telephone","cmsMessage","Telephone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Email = new Field("Email","cmsMessage","Email");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Content = new Field("Content","cmsMessage","Content");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OtherInfo = new Field("OtherInfo","cmsMessage","OtherInfo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MsgIP = new Field("MsgIP","cmsMessage","MsgIP");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddUser = new Field("AddUser","cmsMessage","AddUser");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime","cmsMessage","AddTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsReply = new Field("IsReply","cmsMessage","IsReply");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReplyContent = new Field("ReplyContent","cmsMessage","ReplyContent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReplyUser = new Field("ReplyUser","cmsMessage","ReplyUser");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ReplyTime = new Field("ReplyTime","cmsMessage","ReplyTime");
		}
		#endregion


	}
}

