//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5444
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsMenu 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsMenu : Entity 
	{
		public cmsMenu():base("cmsMenu") {}

		#region Model
		private long _Id;
		private string _MenuCode;
		private string _ParentCode;
		private string _MenuName;
		private string _MenuUrl;
        private int? _MenuType;
		private int? _OrderNo;
		private int? _IsEnabled;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MenuCode
		{
			get{ return _MenuCode; }
			set
			{
				this.OnPropertyValueChange(_.MenuCode,_MenuCode,value);
				this._MenuCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ParentCode
		{
			get{ return _ParentCode; }
			set
			{
				this.OnPropertyValueChange(_.ParentCode,_ParentCode,value);
				this._ParentCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MenuName
		{
			get{ return _MenuName; }
			set
			{
				this.OnPropertyValueChange(_.MenuName,_MenuName,value);
				this._MenuName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MenuUrl
		{
			get{ return _MenuUrl; }
			set
			{
				this.OnPropertyValueChange(_.MenuUrl,_MenuUrl,value);
				this._MenuUrl=value;
			}
		}
        /// <summary>
        /// 
        /// </summary>
        public int? MenuType
        {
            get { return _MenuType; }
            set
            {
                this.OnPropertyValueChange(_.MenuType, _MenuType, value);
                this._MenuType = value;
            }
        }
		/// <summary>
		/// 
		/// </summary>
		public int? OrderNo
		{
			get{ return _OrderNo; }
			set
			{
				this.OnPropertyValueChange(_.OrderNo,_OrderNo,value);
				this._OrderNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? IsEnabled
		{
			get{ return _IsEnabled; }
			set
			{
				this.OnPropertyValueChange(_.IsEnabled,_IsEnabled,value);
				this._IsEnabled=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.MenuCode,
				_.ParentCode,
				_.MenuName,
				_.MenuUrl,
                _.MenuType,
				_.OrderNo,
				_.IsEnabled
            };
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._MenuCode,
				this._ParentCode,
				this._MenuName,
				this._MenuUrl,
                this._MenuType,
				this._OrderNo,
				this._IsEnabled
            };
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._MenuCode = DataUtils.ConvertValue<string>(reader["MenuCode"]);
			this._ParentCode = DataUtils.ConvertValue<string>(reader["ParentCode"]);
			this._MenuName = DataUtils.ConvertValue<string>(reader["MenuName"]);
            this._MenuUrl = DataUtils.ConvertValue<string>(reader["MenuUrl"]);
            this._MenuType = DataUtils.ConvertValue<int?>(reader["MenuType"]);
			this._OrderNo = DataUtils.ConvertValue<int?>(reader["OrderNo"]);
			this._IsEnabled = DataUtils.ConvertValue<int?>(reader["IsEnabled"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._MenuCode = DataUtils.ConvertValue<string>(row["MenuCode"]);
			this._ParentCode = DataUtils.ConvertValue<string>(row["ParentCode"]);
			this._MenuName = DataUtils.ConvertValue<string>(row["MenuName"]);
            this._MenuUrl = DataUtils.ConvertValue<string>(row["MenuUrl"]);
            this._MenuType = DataUtils.ConvertValue<int?>(row["MenuType"]);
			this._OrderNo = DataUtils.ConvertValue<int?>(row["OrderNo"]);
			this._IsEnabled = DataUtils.ConvertValue<int?>(row["IsEnabled"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsMenu");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsMenu","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MenuCode = new Field("MenuCode","cmsMenu","MenuCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentCode = new Field("ParentCode","cmsMenu","ParentCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MenuName = new Field("MenuName","cmsMenu","MenuName");
			/// <summary>
			/// 
			/// </summary>
            public readonly static Field MenuUrl = new Field("MenuUrl", "cmsMenu", "MenuUrl");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MenuType = new Field("MenuType", "cmsMenu", "MenuType");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderNo = new Field("OrderNo","cmsMenu","OrderNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsEnabled = new Field("IsEnabled","cmsMenu","IsEnabled");
		}
		#endregion
	}
}

