//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5444
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsModule 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsModule : Entity 
	{
		public cmsModule():base("cmsModule") {}

		#region Model
		private int _Id;
		private string _Name;
		private string _TableName;
		private string _EntityFullName;
		private string _ServiceFullName;
		private string _Url;
		private string _FrontUrl;
		private int _OrderNo;
		private int _IsEnabled;
		private string _Remark;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TableName
		{
			get{ return _TableName; }
			set
			{
				this.OnPropertyValueChange(_.TableName,_TableName,value);
				this._TableName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string EntityFullName
		{
			get{ return _EntityFullName; }
			set
			{
				this.OnPropertyValueChange(_.EntityFullName,_EntityFullName,value);
				this._EntityFullName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ServiceFullName
		{
			get{ return _ServiceFullName; }
			set
			{
				this.OnPropertyValueChange(_.ServiceFullName,_ServiceFullName,value);
				this._ServiceFullName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Url
		{
			get{ return _Url; }
			set
			{
				this.OnPropertyValueChange(_.Url,_Url,value);
				this._Url=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string FrontUrl
		{
			get{ return _FrontUrl; }
			set
			{
				this.OnPropertyValueChange(_.FrontUrl,_FrontUrl,value);
				this._FrontUrl=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int OrderNo
		{
			get{ return _OrderNo; }
			set
			{
				this.OnPropertyValueChange(_.OrderNo,_OrderNo,value);
				this._OrderNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int IsEnabled
		{
			get{ return _IsEnabled; }
			set
			{
				this.OnPropertyValueChange(_.IsEnabled,_IsEnabled,value);
				this._IsEnabled=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Name,
				_.TableName,
				_.EntityFullName,
				_.ServiceFullName,
				_.Url,
				_.FrontUrl,
				_.OrderNo,
				_.IsEnabled,
				_.Remark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Name,
				this._TableName,
				this._EntityFullName,
				this._ServiceFullName,
				this._Url,
				this._FrontUrl,
				this._OrderNo,
				this._IsEnabled,
				this._Remark};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<int>(reader["Id"]);
			this._Name = DataUtils.ConvertValue<string>(reader["Name"]);
			this._TableName = DataUtils.ConvertValue<string>(reader["TableName"]);
			this._EntityFullName = DataUtils.ConvertValue<string>(reader["EntityFullName"]);
			this._ServiceFullName = DataUtils.ConvertValue<string>(reader["ServiceFullName"]);
			this._Url = DataUtils.ConvertValue<string>(reader["Url"]);
			this._FrontUrl = DataUtils.ConvertValue<string>(reader["FrontUrl"]);
			this._OrderNo = DataUtils.ConvertValue<int>(reader["OrderNo"]);
			this._IsEnabled = DataUtils.ConvertValue<int>(reader["IsEnabled"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<int>(row["Id"]);
			this._Name = DataUtils.ConvertValue<string>(row["Name"]);
			this._TableName = DataUtils.ConvertValue<string>(row["TableName"]);
			this._EntityFullName = DataUtils.ConvertValue<string>(row["EntityFullName"]);
			this._ServiceFullName = DataUtils.ConvertValue<string>(row["ServiceFullName"]);
			this._Url = DataUtils.ConvertValue<string>(row["Url"]);
			this._FrontUrl = DataUtils.ConvertValue<string>(row["FrontUrl"]);
			this._OrderNo = DataUtils.ConvertValue<int>(row["OrderNo"]);
			this._IsEnabled = DataUtils.ConvertValue<int>(row["IsEnabled"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsModule");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsModule","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","cmsModule","Name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TableName = new Field("TableName","cmsModule","TableName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EntityFullName = new Field("EntityFullName","cmsModule","EntityFullName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ServiceFullName = new Field("ServiceFullName","cmsModule","ServiceFullName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Url = new Field("Url","cmsModule","Url");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FrontUrl = new Field("FrontUrl","cmsModule","FrontUrl");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderNo = new Field("OrderNo","cmsModule","OrderNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsEnabled = new Field("IsEnabled","cmsModule","IsEnabled");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark","cmsModule","Remark");
		}
		#endregion


	}
}

