//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5444
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsNewsTopicRel 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsNewsTopicRel : Entity 
	{
		public cmsNewsTopicRel():base("cmsNewsTopicRel") {}

		#region Model
		private long _TopicId;
		private string _NewsId;
		/// <summary>
		/// 
		/// </summary>
		public long TopicId
		{
			get{ return _TopicId; }
			set
			{
				this.OnPropertyValueChange(_.TopicId,_TopicId,value);
				this._TopicId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string NewsId
		{
			get{ return _NewsId; }
			set
			{
				this.OnPropertyValueChange(_.NewsId,_NewsId,value);
				this._NewsId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.TopicId,
				_.NewsId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._TopicId,
				this._NewsId};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._TopicId = DataUtils.ConvertValue<long>(reader["TopicId"]);
			this._NewsId = DataUtils.ConvertValue<string>(reader["NewsId"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._TopicId = DataUtils.ConvertValue<long>(row["TopicId"]);
			this._NewsId = DataUtils.ConvertValue<string>(row["NewsId"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsNewsTopicRel");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TopicId = new Field("TopicId","cmsNewsTopicRel","TopicId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NewsId = new Field("NewsId","cmsNewsTopicRel","NewsId");
		}
		#endregion


	}
}

