//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5444
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsNewsCatalog 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsNewsCatalog : Entity 
	{
		public cmsNewsCatalog():base("cmsNewsCatalog") {}

		#region Model
		private long _Id;
		private string _NodeCode;
		private string _ParentCode;
		private string _NodeName;
		private int _NodeType;
        private string _Title;
        private string _SubTitle;
		private string _SmallPic;
		private string _BigPic;
		private string _BackUrl;
		private string _LinkUrl;
		private int _OrderNo;
		private int _NavType;
		private int _IsEnabled;
		private long _LangId;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string NodeCode
		{
			get{ return _NodeCode; }
			set
			{
				this.OnPropertyValueChange(_.NodeCode,_NodeCode,value);
				this._NodeCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ParentCode
		{
			get{ return _ParentCode; }
			set
			{
				this.OnPropertyValueChange(_.ParentCode,_ParentCode,value);
				this._ParentCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string NodeName
		{
			get{ return _NodeName; }
			set
			{
				this.OnPropertyValueChange(_.NodeName,_NodeName,value);
				this._NodeName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int NodeType
		{
			get{ return _NodeType; }
			set
			{
				this.OnPropertyValueChange(_.NodeType,_NodeType,value);
				this._NodeType=value;
			}
		}
        /// <summary>
        /// 
        /// </summary>
        public string Title
        {
            get { return _Title; }
            set
            {
                this.OnPropertyValueChange(_.Title, _Title, value);
                this._Title = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SubTitle
        {
            get { return _SubTitle; }
            set
            {
                this.OnPropertyValueChange(_.SubTitle, _SubTitle, value);
                this._SubTitle = value;
            }
        }
		/// <summary>
		/// 
		/// </summary>
		public string SmallPic
		{
			get{ return _SmallPic; }
			set
			{
				this.OnPropertyValueChange(_.SmallPic,_SmallPic,value);
				this._SmallPic=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string BigPic
		{
			get{ return _BigPic; }
			set
			{
				this.OnPropertyValueChange(_.BigPic,_BigPic,value);
				this._BigPic=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string BackUrl
		{
			get{ return _BackUrl; }
			set
			{
				this.OnPropertyValueChange(_.BackUrl,_BackUrl,value);
				this._BackUrl=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string LinkUrl
		{
			get{ return _LinkUrl; }
			set
			{
				this.OnPropertyValueChange(_.LinkUrl,_LinkUrl,value);
				this._LinkUrl=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int OrderNo
		{
			get{ return _OrderNo; }
			set
			{
				this.OnPropertyValueChange(_.OrderNo,_OrderNo,value);
				this._OrderNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int NavType
		{
			get{ return _NavType; }
			set
			{
				this.OnPropertyValueChange(_.NavType,_NavType,value);
				this._NavType=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int IsEnabled
		{
			get{ return _IsEnabled; }
			set
			{
				this.OnPropertyValueChange(_.IsEnabled,_IsEnabled,value);
				this._IsEnabled=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long LangId
		{
			get{ return _LangId; }
			set
			{
				this.OnPropertyValueChange(_.LangId,_LangId,value);
				this._LangId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.NodeCode,
				_.ParentCode,
				_.NodeName,
				_.NodeType,
                _.Title,
                _.SubTitle,
				_.SmallPic,
				_.BigPic,
				_.BackUrl,
				_.LinkUrl,
				_.OrderNo,
				_.NavType,
				_.IsEnabled,
				_.LangId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._NodeCode,
				this._ParentCode,
				this._NodeName,
				this._NodeType,
                this._Title,
                this._SubTitle,
				this._SmallPic,
				this._BigPic,
				this._BackUrl,
				this._LinkUrl,
				this._OrderNo,
				this._NavType,
				this._IsEnabled,
				this._LangId};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._NodeCode = DataUtils.ConvertValue<string>(reader["NodeCode"]);
			this._ParentCode = DataUtils.ConvertValue<string>(reader["ParentCode"]);
			this._NodeName = DataUtils.ConvertValue<string>(reader["NodeName"]);
            this._NodeType = DataUtils.ConvertValue<int>(reader["NodeType"]);
            this._Title = DataUtils.ConvertValue<string>(reader["Title"]);
            this._SubTitle = DataUtils.ConvertValue<string>(reader["SubTitle"]);
			this._SmallPic = DataUtils.ConvertValue<string>(reader["SmallPic"]);
			this._BigPic = DataUtils.ConvertValue<string>(reader["BigPic"]);
			this._BackUrl = DataUtils.ConvertValue<string>(reader["BackUrl"]);
			this._LinkUrl = DataUtils.ConvertValue<string>(reader["LinkUrl"]);
			this._OrderNo = DataUtils.ConvertValue<int>(reader["OrderNo"]);
			this._NavType = DataUtils.ConvertValue<int>(reader["NavType"]);
			this._IsEnabled = DataUtils.ConvertValue<int>(reader["IsEnabled"]);
			this._LangId = DataUtils.ConvertValue<long>(reader["LangId"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._NodeCode = DataUtils.ConvertValue<string>(row["NodeCode"]);
			this._ParentCode = DataUtils.ConvertValue<string>(row["ParentCode"]);
			this._NodeName = DataUtils.ConvertValue<string>(row["NodeName"]);
            this._NodeType = DataUtils.ConvertValue<int>(row["NodeType"]);
            this._Title = DataUtils.ConvertValue<string>(row["Title"]);
            this._SubTitle = DataUtils.ConvertValue<string>(row["SubTitle"]);
			this._SmallPic = DataUtils.ConvertValue<string>(row["SmallPic"]);
			this._BigPic = DataUtils.ConvertValue<string>(row["BigPic"]);
			this._BackUrl = DataUtils.ConvertValue<string>(row["BackUrl"]);
			this._LinkUrl = DataUtils.ConvertValue<string>(row["LinkUrl"]);
			this._OrderNo = DataUtils.ConvertValue<int>(row["OrderNo"]);
			this._NavType = DataUtils.ConvertValue<int>(row["NavType"]);
			this._IsEnabled = DataUtils.ConvertValue<int>(row["IsEnabled"]);
			this._LangId = DataUtils.ConvertValue<long>(row["LangId"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsNewsCatalog");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsNewsCatalog","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NodeCode = new Field("NodeCode","cmsNewsCatalog","NodeCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentCode = new Field("ParentCode","cmsNewsCatalog","ParentCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NodeName = new Field("NodeName","cmsNewsCatalog","NodeName");
			/// <summary>
			/// 
			/// </summary>
            public readonly static Field NodeType = new Field("NodeType", "cmsNewsCatalog", "NodeType");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Title = new Field("Title", "cmsNewsCatalog", "Title");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SubTitle = new Field("SubTitle", "cmsNewsCatalog", "SubTitle");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SmallPic = new Field("SmallPic","cmsNewsCatalog","SmallPic");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BigPic = new Field("BigPic","cmsNewsCatalog","BigPic");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BackUrl = new Field("BackUrl","cmsNewsCatalog","BackUrl");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LinkUrl = new Field("LinkUrl","cmsNewsCatalog","LinkUrl");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderNo = new Field("OrderNo","cmsNewsCatalog","OrderNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NavType = new Field("NavType","cmsNewsCatalog","NavType");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsEnabled = new Field("IsEnabled","cmsNewsCatalog","IsEnabled");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LangId = new Field("LangId","cmsNewsCatalog","LangId");
		}
		#endregion
	}
}

