//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsNews 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsNews : Entity 
	{
		public cmsNews():base("cmsNews") {}

		#region Model
		private long _Id;
		private string _RGuid;
		private string _NodeCode;
		private string _Title;
		private string _Content;
		private string _Summary;
		private string _Tags;
		private string _Author;
		private string _Source;
		private string _SmallPic;
		private string _Pics;
		private int _Hits;
		private DateTime _AddTime;
		private long _AddUser;
		private DateTime _EditTime;
		private long _EditUser;
		private int _OrderNo;
		private int _IsIndex;
		private int _IsTop;
		private int _IsAudit;
		private DateTime _AuditTime;
		private long _AuditUser;
		private string _AuditComment;
		private string _ProductNo;
		private string _ProductModel;
		private string _Parameter1;
		private string _Parameter2;
		private string _Parameter3;
		private string _Parameter4;
		private string _Parameter5;
		private string _Parameter6;
		private string _Parameter7;
		private string _Parameter8;
		private string _Parameter9;
		private long _LangId;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RGuid
		{
			get{ return _RGuid; }
			set
			{
				this.OnPropertyValueChange(_.RGuid,_RGuid,value);
				this._RGuid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string NodeCode
		{
			get{ return _NodeCode; }
			set
			{
				this.OnPropertyValueChange(_.NodeCode,_NodeCode,value);
				this._NodeCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Summary
		{
			get{ return _Summary; }
			set
			{
				this.OnPropertyValueChange(_.Summary,_Summary,value);
				this._Summary=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Tags
		{
			get{ return _Tags; }
			set
			{
				this.OnPropertyValueChange(_.Tags,_Tags,value);
				this._Tags=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Author
		{
			get{ return _Author; }
			set
			{
				this.OnPropertyValueChange(_.Author,_Author,value);
				this._Author=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Source
		{
			get{ return _Source; }
			set
			{
				this.OnPropertyValueChange(_.Source,_Source,value);
				this._Source=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SmallPic
		{
			get{ return _SmallPic; }
			set
			{
				this.OnPropertyValueChange(_.SmallPic,_SmallPic,value);
				this._SmallPic=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Pics
		{
			get{ return _Pics; }
			set
			{
				this.OnPropertyValueChange(_.Pics,_Pics,value);
				this._Pics=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int Hits
		{
			get{ return _Hits; }
			set
			{
				this.OnPropertyValueChange(_.Hits,_Hits,value);
				this._Hits=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime AddTime
		{
			get{ return _AddTime; }
			set
			{
				this.OnPropertyValueChange(_.AddTime,_AddTime,value);
				this._AddTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long AddUser
		{
			get{ return _AddUser; }
			set
			{
				this.OnPropertyValueChange(_.AddUser,_AddUser,value);
				this._AddUser=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime EditTime
		{
			get{ return _EditTime; }
			set
			{
				this.OnPropertyValueChange(_.EditTime,_EditTime,value);
				this._EditTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long EditUser
		{
			get{ return _EditUser; }
			set
			{
				this.OnPropertyValueChange(_.EditUser,_EditUser,value);
				this._EditUser=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int OrderNo
		{
			get{ return _OrderNo; }
			set
			{
				this.OnPropertyValueChange(_.OrderNo,_OrderNo,value);
				this._OrderNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int IsIndex
		{
			get{ return _IsIndex; }
			set
			{
				this.OnPropertyValueChange(_.IsIndex,_IsIndex,value);
				this._IsIndex=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int IsTop
		{
			get{ return _IsTop; }
			set
			{
				this.OnPropertyValueChange(_.IsTop,_IsTop,value);
				this._IsTop=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int IsAudit
		{
			get{ return _IsAudit; }
			set
			{
				this.OnPropertyValueChange(_.IsAudit,_IsAudit,value);
				this._IsAudit=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime AuditTime
		{
			get{ return _AuditTime; }
			set
			{
				this.OnPropertyValueChange(_.AuditTime,_AuditTime,value);
				this._AuditTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long AuditUser
		{
			get{ return _AuditUser; }
			set
			{
				this.OnPropertyValueChange(_.AuditUser,_AuditUser,value);
				this._AuditUser=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AuditComment
		{
			get{ return _AuditComment; }
			set
			{
				this.OnPropertyValueChange(_.AuditComment,_AuditComment,value);
				this._AuditComment=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ProductNo
		{
			get{ return _ProductNo; }
			set
			{
				this.OnPropertyValueChange(_.ProductNo,_ProductNo,value);
				this._ProductNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ProductModel
		{
			get{ return _ProductModel; }
			set
			{
				this.OnPropertyValueChange(_.ProductModel,_ProductModel,value);
				this._ProductModel=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Parameter1
		{
			get{ return _Parameter1; }
			set
			{
				this.OnPropertyValueChange(_.Parameter1,_Parameter1,value);
				this._Parameter1=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Parameter2
		{
			get{ return _Parameter2; }
			set
			{
				this.OnPropertyValueChange(_.Parameter2,_Parameter2,value);
				this._Parameter2=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Parameter3
		{
			get{ return _Parameter3; }
			set
			{
				this.OnPropertyValueChange(_.Parameter3,_Parameter3,value);
				this._Parameter3=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Parameter4
		{
			get{ return _Parameter4; }
			set
			{
				this.OnPropertyValueChange(_.Parameter4,_Parameter4,value);
				this._Parameter4=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Parameter5
		{
			get{ return _Parameter5; }
			set
			{
				this.OnPropertyValueChange(_.Parameter5,_Parameter5,value);
				this._Parameter5=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Parameter6
		{
			get{ return _Parameter6; }
			set
			{
				this.OnPropertyValueChange(_.Parameter6,_Parameter6,value);
				this._Parameter6=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Parameter7
		{
			get{ return _Parameter7; }
			set
			{
				this.OnPropertyValueChange(_.Parameter7,_Parameter7,value);
				this._Parameter7=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Parameter8
		{
			get{ return _Parameter8; }
			set
			{
				this.OnPropertyValueChange(_.Parameter8,_Parameter8,value);
				this._Parameter8=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Parameter9
		{
			get{ return _Parameter9; }
			set
			{
				this.OnPropertyValueChange(_.Parameter9,_Parameter9,value);
				this._Parameter9=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long LangId
		{
			get{ return _LangId; }
			set
			{
				this.OnPropertyValueChange(_.LangId,_LangId,value);
				this._LangId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.RGuid,
				_.NodeCode,
				_.Title,
				_.Content,
				_.Summary,
				_.Tags,
				_.Author,
				_.Source,
				_.SmallPic,
				_.Pics,
				_.Hits,
				_.AddTime,
				_.AddUser,
				_.EditTime,
				_.EditUser,
				_.OrderNo,
				_.IsIndex,
				_.IsTop,
				_.IsAudit,
				_.AuditTime,
				_.AuditUser,
				_.AuditComment,
				_.ProductNo,
				_.ProductModel,
				_.Parameter1,
				_.Parameter2,
				_.Parameter3,
				_.Parameter4,
				_.Parameter5,
				_.Parameter6,
				_.Parameter7,
				_.Parameter8,
				_.Parameter9,
				_.LangId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._RGuid,
				this._NodeCode,
				this._Title,
				this._Content,
				this._Summary,
				this._Tags,
				this._Author,
				this._Source,
				this._SmallPic,
				this._Pics,
				this._Hits,
				this._AddTime,
				this._AddUser,
				this._EditTime,
				this._EditUser,
				this._OrderNo,
				this._IsIndex,
				this._IsTop,
				this._IsAudit,
				this._AuditTime,
				this._AuditUser,
				this._AuditComment,
				this._ProductNo,
				this._ProductModel,
				this._Parameter1,
				this._Parameter2,
				this._Parameter3,
				this._Parameter4,
				this._Parameter5,
				this._Parameter6,
				this._Parameter7,
				this._Parameter8,
				this._Parameter9,
				this._LangId};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._RGuid = DataUtils.ConvertValue<string>(reader["RGuid"]);
			this._NodeCode = DataUtils.ConvertValue<string>(reader["NodeCode"]);
			this._Title = DataUtils.ConvertValue<string>(reader["Title"]);
			this._Content = DataUtils.ConvertValue<string>(reader["Content"]);
			this._Summary = DataUtils.ConvertValue<string>(reader["Summary"]);
			this._Tags = DataUtils.ConvertValue<string>(reader["Tags"]);
			this._Author = DataUtils.ConvertValue<string>(reader["Author"]);
			this._Source = DataUtils.ConvertValue<string>(reader["Source"]);
			this._SmallPic = DataUtils.ConvertValue<string>(reader["SmallPic"]);
			this._Pics = DataUtils.ConvertValue<string>(reader["Pics"]);
			this._Hits = DataUtils.ConvertValue<int>(reader["Hits"]);
			this._AddTime = DataUtils.ConvertValue<DateTime>(reader["AddTime"]);
			this._AddUser = DataUtils.ConvertValue<long>(reader["AddUser"]);
			this._EditTime = DataUtils.ConvertValue<DateTime>(reader["EditTime"]);
			this._EditUser = DataUtils.ConvertValue<long>(reader["EditUser"]);
			this._OrderNo = DataUtils.ConvertValue<int>(reader["OrderNo"]);
			this._IsIndex = DataUtils.ConvertValue<int>(reader["IsIndex"]);
			this._IsTop = DataUtils.ConvertValue<int>(reader["IsTop"]);
			this._IsAudit = DataUtils.ConvertValue<int>(reader["IsAudit"]);
			this._AuditTime = DataUtils.ConvertValue<DateTime>(reader["AuditTime"]);
			this._AuditUser = DataUtils.ConvertValue<long>(reader["AuditUser"]);
			this._AuditComment = DataUtils.ConvertValue<string>(reader["AuditComment"]);
			this._ProductNo = DataUtils.ConvertValue<string>(reader["ProductNo"]);
			this._ProductModel = DataUtils.ConvertValue<string>(reader["ProductModel"]);
			this._Parameter1 = DataUtils.ConvertValue<string>(reader["Parameter1"]);
			this._Parameter2 = DataUtils.ConvertValue<string>(reader["Parameter2"]);
			this._Parameter3 = DataUtils.ConvertValue<string>(reader["Parameter3"]);
			this._Parameter4 = DataUtils.ConvertValue<string>(reader["Parameter4"]);
			this._Parameter5 = DataUtils.ConvertValue<string>(reader["Parameter5"]);
			this._Parameter6 = DataUtils.ConvertValue<string>(reader["Parameter6"]);
			this._Parameter7 = DataUtils.ConvertValue<string>(reader["Parameter7"]);
			this._Parameter8 = DataUtils.ConvertValue<string>(reader["Parameter8"]);
			this._Parameter9 = DataUtils.ConvertValue<string>(reader["Parameter9"]);
			this._LangId = DataUtils.ConvertValue<long>(reader["LangId"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._RGuid = DataUtils.ConvertValue<string>(row["RGuid"]);
			this._NodeCode = DataUtils.ConvertValue<string>(row["NodeCode"]);
			this._Title = DataUtils.ConvertValue<string>(row["Title"]);
			this._Content = DataUtils.ConvertValue<string>(row["Content"]);
			this._Summary = DataUtils.ConvertValue<string>(row["Summary"]);
			this._Tags = DataUtils.ConvertValue<string>(row["Tags"]);
			this._Author = DataUtils.ConvertValue<string>(row["Author"]);
			this._Source = DataUtils.ConvertValue<string>(row["Source"]);
			this._SmallPic = DataUtils.ConvertValue<string>(row["SmallPic"]);
			this._Pics = DataUtils.ConvertValue<string>(row["Pics"]);
			this._Hits = DataUtils.ConvertValue<int>(row["Hits"]);
			this._AddTime = DataUtils.ConvertValue<DateTime>(row["AddTime"]);
			this._AddUser = DataUtils.ConvertValue<long>(row["AddUser"]);
			this._EditTime = DataUtils.ConvertValue<DateTime>(row["EditTime"]);
			this._EditUser = DataUtils.ConvertValue<long>(row["EditUser"]);
			this._OrderNo = DataUtils.ConvertValue<int>(row["OrderNo"]);
			this._IsIndex = DataUtils.ConvertValue<int>(row["IsIndex"]);
			this._IsTop = DataUtils.ConvertValue<int>(row["IsTop"]);
			this._IsAudit = DataUtils.ConvertValue<int>(row["IsAudit"]);
			this._AuditTime = DataUtils.ConvertValue<DateTime>(row["AuditTime"]);
			this._AuditUser = DataUtils.ConvertValue<long>(row["AuditUser"]);
			this._AuditComment = DataUtils.ConvertValue<string>(row["AuditComment"]);
			this._ProductNo = DataUtils.ConvertValue<string>(row["ProductNo"]);
			this._ProductModel = DataUtils.ConvertValue<string>(row["ProductModel"]);
			this._Parameter1 = DataUtils.ConvertValue<string>(row["Parameter1"]);
			this._Parameter2 = DataUtils.ConvertValue<string>(row["Parameter2"]);
			this._Parameter3 = DataUtils.ConvertValue<string>(row["Parameter3"]);
			this._Parameter4 = DataUtils.ConvertValue<string>(row["Parameter4"]);
			this._Parameter5 = DataUtils.ConvertValue<string>(row["Parameter5"]);
			this._Parameter6 = DataUtils.ConvertValue<string>(row["Parameter6"]);
			this._Parameter7 = DataUtils.ConvertValue<string>(row["Parameter7"]);
			this._Parameter8 = DataUtils.ConvertValue<string>(row["Parameter8"]);
			this._Parameter9 = DataUtils.ConvertValue<string>(row["Parameter9"]);
			this._LangId = DataUtils.ConvertValue<long>(row["LangId"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsNews");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsNews","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RGuid = new Field("RGuid","cmsNews","RGuid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NodeCode = new Field("NodeCode","cmsNews","NodeCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","cmsNews","Title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Content = new Field("Content","cmsNews","Content");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Summary = new Field("Summary","cmsNews","Summary");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Tags = new Field("Tags","cmsNews","Tags");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Author = new Field("Author","cmsNews","Author");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Source = new Field("Source","cmsNews","Source");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SmallPic = new Field("SmallPic","cmsNews","SmallPic");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Pics = new Field("Pics","cmsNews","Pics");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Hits = new Field("Hits","cmsNews","Hits");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime","cmsNews","AddTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddUser = new Field("AddUser","cmsNews","AddUser");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EditTime = new Field("EditTime","cmsNews","EditTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EditUser = new Field("EditUser","cmsNews","EditUser");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderNo = new Field("OrderNo","cmsNews","OrderNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsIndex = new Field("IsIndex","cmsNews","IsIndex");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsTop = new Field("IsTop","cmsNews","IsTop");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsAudit = new Field("IsAudit","cmsNews","IsAudit");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AuditTime = new Field("AuditTime","cmsNews","AuditTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AuditUser = new Field("AuditUser","cmsNews","AuditUser");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AuditComment = new Field("AuditComment","cmsNews","AuditComment");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ProductNo = new Field("ProductNo","cmsNews","ProductNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ProductModel = new Field("ProductModel","cmsNews","ProductModel");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Parameter1 = new Field("Parameter1","cmsNews","Parameter1");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Parameter2 = new Field("Parameter2","cmsNews","Parameter2");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Parameter3 = new Field("Parameter3","cmsNews","Parameter3");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Parameter4 = new Field("Parameter4","cmsNews","Parameter4");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Parameter5 = new Field("Parameter5","cmsNews","Parameter5");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Parameter6 = new Field("Parameter6","cmsNews","Parameter6");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Parameter7 = new Field("Parameter7","cmsNews","Parameter7");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Parameter8 = new Field("Parameter8","cmsNews","Parameter8");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Parameter9 = new Field("Parameter9","cmsNews","Parameter9");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LangId = new Field("LangId","cmsNews","LangId");
		}
		#endregion


	}
}

