//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsResource 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsResource : Entity 
	{
		public cmsResource():base("cmsResource") {}

		#region Model
		private long _ResId;
		private string _ResCode;
		private string _ResType;
		private string _ResName;
		private string _ResValue;
		private long _LangId;
		/// <summary>
		/// 
		/// </summary>
		public long ResId
		{
			get{ return _ResId; }
			set
			{
				this.OnPropertyValueChange(_.ResId,_ResId,value);
				this._ResId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ResCode
		{
			get{ return _ResCode; }
			set
			{
				this.OnPropertyValueChange(_.ResCode,_ResCode,value);
				this._ResCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ResType
		{
			get{ return _ResType; }
			set
			{
				this.OnPropertyValueChange(_.ResType,_ResType,value);
				this._ResType=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ResName
		{
			get{ return _ResName; }
			set
			{
				this.OnPropertyValueChange(_.ResName,_ResName,value);
				this._ResName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ResValue
		{
			get{ return _ResValue; }
			set
			{
				this.OnPropertyValueChange(_.ResValue,_ResValue,value);
				this._ResValue=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long LangId
		{
			get{ return _LangId; }
			set
			{
				this.OnPropertyValueChange(_.LangId,_LangId,value);
				this._LangId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ResId;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ResId};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ResId,
				_.ResCode,
				_.ResType,
				_.ResName,
				_.ResValue,
				_.LangId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ResId,
				this._ResCode,
				this._ResType,
				this._ResName,
				this._ResValue,
				this._LangId};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._ResId = DataUtils.ConvertValue<long>(reader["ResId"]);
			this._ResCode = DataUtils.ConvertValue<string>(reader["ResCode"]);
			this._ResType = DataUtils.ConvertValue<string>(reader["ResType"]);
			this._ResName = DataUtils.ConvertValue<string>(reader["ResName"]);
			this._ResValue = DataUtils.ConvertValue<string>(reader["ResValue"]);
			this._LangId = DataUtils.ConvertValue<long>(reader["LangId"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._ResId = DataUtils.ConvertValue<long>(row["ResId"]);
			this._ResCode = DataUtils.ConvertValue<string>(row["ResCode"]);
			this._ResType = DataUtils.ConvertValue<string>(row["ResType"]);
			this._ResName = DataUtils.ConvertValue<string>(row["ResName"]);
			this._ResValue = DataUtils.ConvertValue<string>(row["ResValue"]);
			this._LangId = DataUtils.ConvertValue<long>(row["LangId"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsResource");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ResId = new Field("ResId","cmsResource","ResId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ResCode = new Field("ResCode","cmsResource","ResCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ResType = new Field("ResType","cmsResource","ResType");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ResName = new Field("ResName","cmsResource","ResName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ResValue = new Field("ResValue","cmsResource","ResValue");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LangId = new Field("LangId","cmsResource","LangId");
		}
		#endregion


	}
}

