//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5444
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsServicer 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsServicer : Entity 
	{
		public cmsServicer():base("cmsServicer") {}

		#region Model
		private long _Id;
		private string _Name;
		private string _QQ;
		private string _MSN;
		private string _TaobaoWW;
		private string _AliWW;
		private string _SKYPE;
		private int? _OrderNo;
		private int? _IsEnabled;
		private long? _LangId;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string QQ
		{
			get{ return _QQ; }
			set
			{
				this.OnPropertyValueChange(_.QQ,_QQ,value);
				this._QQ=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MSN
		{
			get{ return _MSN; }
			set
			{
				this.OnPropertyValueChange(_.MSN,_MSN,value);
				this._MSN=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TaobaoWW
		{
			get{ return _TaobaoWW; }
			set
			{
				this.OnPropertyValueChange(_.TaobaoWW,_TaobaoWW,value);
				this._TaobaoWW=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AliWW
		{
			get{ return _AliWW; }
			set
			{
				this.OnPropertyValueChange(_.AliWW,_AliWW,value);
				this._AliWW=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SKYPE
		{
			get{ return _SKYPE; }
			set
			{
				this.OnPropertyValueChange(_.SKYPE,_SKYPE,value);
				this._SKYPE=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? OrderNo
		{
			get{ return _OrderNo; }
			set
			{
				this.OnPropertyValueChange(_.OrderNo,_OrderNo,value);
				this._OrderNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? IsEnabled
		{
			get{ return _IsEnabled; }
			set
			{
				this.OnPropertyValueChange(_.IsEnabled,_IsEnabled,value);
				this._IsEnabled=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long? LangId
		{
			get{ return _LangId; }
			set
			{
				this.OnPropertyValueChange(_.LangId,_LangId,value);
				this._LangId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Name,
				_.QQ,
				_.MSN,
				_.TaobaoWW,
				_.AliWW,
				_.SKYPE,
				_.OrderNo,
				_.IsEnabled,
				_.LangId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Name,
				this._QQ,
				this._MSN,
				this._TaobaoWW,
				this._AliWW,
				this._SKYPE,
				this._OrderNo,
				this._IsEnabled,
				this._LangId};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._Name = DataUtils.ConvertValue<string>(reader["Name"]);
			this._QQ = DataUtils.ConvertValue<string>(reader["QQ"]);
			this._MSN = DataUtils.ConvertValue<string>(reader["MSN"]);
			this._TaobaoWW = DataUtils.ConvertValue<string>(reader["TaobaoWW"]);
			this._AliWW = DataUtils.ConvertValue<string>(reader["AliWW"]);
			this._SKYPE = DataUtils.ConvertValue<string>(reader["SKYPE"]);
			this._OrderNo = DataUtils.ConvertValue<int?>(reader["OrderNo"]);
			this._IsEnabled = DataUtils.ConvertValue<int?>(reader["IsEnabled"]);
			this._LangId = DataUtils.ConvertValue<long?>(reader["LangId"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._Name = DataUtils.ConvertValue<string>(row["Name"]);
			this._QQ = DataUtils.ConvertValue<string>(row["QQ"]);
			this._MSN = DataUtils.ConvertValue<string>(row["MSN"]);
			this._TaobaoWW = DataUtils.ConvertValue<string>(row["TaobaoWW"]);
			this._AliWW = DataUtils.ConvertValue<string>(row["AliWW"]);
			this._SKYPE = DataUtils.ConvertValue<string>(row["SKYPE"]);
			this._OrderNo = DataUtils.ConvertValue<int?>(row["OrderNo"]);
			this._IsEnabled = DataUtils.ConvertValue<int?>(row["IsEnabled"]);
			this._LangId = DataUtils.ConvertValue<long?>(row["LangId"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsServicer");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsServicer","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name","cmsServicer","Name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field QQ = new Field("QQ","cmsServicer","QQ");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MSN = new Field("MSN","cmsServicer","MSN");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TaobaoWW = new Field("TaobaoWW","cmsServicer","TaobaoWW");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AliWW = new Field("AliWW","cmsServicer","AliWW");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SKYPE = new Field("SKYPE","cmsServicer","SKYPE");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderNo = new Field("OrderNo","cmsServicer","OrderNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsEnabled = new Field("IsEnabled","cmsServicer","IsEnabled");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LangId = new Field("LangId","cmsServicer","LangId");
		}
		#endregion


	}
}

