//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsSlideshow 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsSlideshow : Entity 
	{
		public cmsSlideshow():base("cmsSlideshow") {}

		#region Model
		private long _Id;
		private string _Title;
		private string _Summary;
		private string _ImgSrc;
		private string _ImgThumb;
		private string _Url;
		private string _Target;
		private int _OrderNo;
		private int _IsEnabled;
		private DateTime _AddTime;
		private long _LangId;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Summary
		{
			get{ return _Summary; }
			set
			{
				this.OnPropertyValueChange(_.Summary,_Summary,value);
				this._Summary=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ImgSrc
		{
			get{ return _ImgSrc; }
			set
			{
				this.OnPropertyValueChange(_.ImgSrc,_ImgSrc,value);
				this._ImgSrc=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ImgThumb
		{
			get{ return _ImgThumb; }
			set
			{
				this.OnPropertyValueChange(_.ImgThumb,_ImgThumb,value);
				this._ImgThumb=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Url
		{
			get{ return _Url; }
			set
			{
				this.OnPropertyValueChange(_.Url,_Url,value);
				this._Url=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Target
		{
			get{ return _Target; }
			set
			{
				this.OnPropertyValueChange(_.Target,_Target,value);
				this._Target=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int OrderNo
		{
			get{ return _OrderNo; }
			set
			{
				this.OnPropertyValueChange(_.OrderNo,_OrderNo,value);
				this._OrderNo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int IsEnabled
		{
			get{ return _IsEnabled; }
			set
			{
				this.OnPropertyValueChange(_.IsEnabled,_IsEnabled,value);
				this._IsEnabled=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime AddTime
		{
			get{ return _AddTime; }
			set
			{
				this.OnPropertyValueChange(_.AddTime,_AddTime,value);
				this._AddTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long LangId
		{
			get{ return _LangId; }
			set
			{
				this.OnPropertyValueChange(_.LangId,_LangId,value);
				this._LangId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Title,
				_.Summary,
				_.ImgSrc,
				_.ImgThumb,
				_.Url,
				_.Target,
				_.OrderNo,
				_.IsEnabled,
				_.AddTime,
				_.LangId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Title,
				this._Summary,
				this._ImgSrc,
				this._ImgThumb,
				this._Url,
				this._Target,
				this._OrderNo,
				this._IsEnabled,
				this._AddTime,
				this._LangId};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._Title = DataUtils.ConvertValue<string>(reader["Title"]);
			this._Summary = DataUtils.ConvertValue<string>(reader["Summary"]);
			this._ImgSrc = DataUtils.ConvertValue<string>(reader["ImgSrc"]);
			this._ImgThumb = DataUtils.ConvertValue<string>(reader["ImgThumb"]);
			this._Url = DataUtils.ConvertValue<string>(reader["Url"]);
			this._Target = DataUtils.ConvertValue<string>(reader["Target"]);
			this._OrderNo = DataUtils.ConvertValue<int>(reader["OrderNo"]);
			this._IsEnabled = DataUtils.ConvertValue<int>(reader["IsEnabled"]);
			this._AddTime = DataUtils.ConvertValue<DateTime>(reader["AddTime"]);
			this._LangId = DataUtils.ConvertValue<long>(reader["LangId"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._Title = DataUtils.ConvertValue<string>(row["Title"]);
			this._Summary = DataUtils.ConvertValue<string>(row["Summary"]);
			this._ImgSrc = DataUtils.ConvertValue<string>(row["ImgSrc"]);
			this._ImgThumb = DataUtils.ConvertValue<string>(row["ImgThumb"]);
			this._Url = DataUtils.ConvertValue<string>(row["Url"]);
			this._Target = DataUtils.ConvertValue<string>(row["Target"]);
			this._OrderNo = DataUtils.ConvertValue<int>(row["OrderNo"]);
			this._IsEnabled = DataUtils.ConvertValue<int>(row["IsEnabled"]);
			this._AddTime = DataUtils.ConvertValue<DateTime>(row["AddTime"]);
			this._LangId = DataUtils.ConvertValue<long>(row["LangId"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsSlideshow");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsSlideshow","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","cmsSlideshow","Title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Summary = new Field("Summary","cmsSlideshow","Summary");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ImgSrc = new Field("ImgSrc","cmsSlideshow","ImgSrc");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ImgThumb = new Field("ImgThumb","cmsSlideshow","ImgThumb");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Url = new Field("Url","cmsSlideshow","Url");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Target = new Field("Target","cmsSlideshow","Target");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderNo = new Field("OrderNo","cmsSlideshow","OrderNo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsEnabled = new Field("IsEnabled","cmsSlideshow","IsEnabled");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime","cmsSlideshow","AddTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LangId = new Field("LangId","cmsSlideshow","LangId");
		}
		#endregion


	}
}

