//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5444
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsVote 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsVote : Entity 
	{
		public cmsVote():base("cmsVote") {}

		#region Model
		private long _Id;
		private string _Title;
		private string _Summary;
		private int? _Type;
		private int? _MaxSels;
		private int? _Total;
		private DateTime? _StartDate;
		private DateTime? _EndDate;
		private int? _IsEnabled;
		private int? _CreateUser;
		private DateTime? _CreateTime;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Summary
		{
			get{ return _Summary; }
			set
			{
				this.OnPropertyValueChange(_.Summary,_Summary,value);
				this._Summary=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange(_.Type,_Type,value);
				this._Type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MaxSels
		{
			get{ return _MaxSels; }
			set
			{
				this.OnPropertyValueChange(_.MaxSels,_MaxSels,value);
				this._MaxSels=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Total
		{
			get{ return _Total; }
			set
			{
				this.OnPropertyValueChange(_.Total,_Total,value);
				this._Total=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? StartDate
		{
			get{ return _StartDate; }
			set
			{
				this.OnPropertyValueChange(_.StartDate,_StartDate,value);
				this._StartDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? EndDate
		{
			get{ return _EndDate; }
			set
			{
				this.OnPropertyValueChange(_.EndDate,_EndDate,value);
				this._EndDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? IsEnabled
		{
			get{ return _IsEnabled; }
			set
			{
				this.OnPropertyValueChange(_.IsEnabled,_IsEnabled,value);
				this._IsEnabled=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CreateUser
		{
			get{ return _CreateUser; }
			set
			{
				this.OnPropertyValueChange(_.CreateUser,_CreateUser,value);
				this._CreateUser=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Title,
				_.Summary,
				_.Type,
				_.MaxSels,
				_.Total,
				_.StartDate,
				_.EndDate,
				_.IsEnabled,
				_.CreateUser,
				_.CreateTime};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Title,
				this._Summary,
				this._Type,
				this._MaxSels,
				this._Total,
				this._StartDate,
				this._EndDate,
				this._IsEnabled,
				this._CreateUser,
				this._CreateTime};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._Title = DataUtils.ConvertValue<string>(reader["Title"]);
			this._Summary = DataUtils.ConvertValue<string>(reader["Summary"]);
			this._Type = DataUtils.ConvertValue<int?>(reader["Type"]);
			this._MaxSels = DataUtils.ConvertValue<int?>(reader["MaxSels"]);
			this._Total = DataUtils.ConvertValue<int?>(reader["Total"]);
			this._StartDate = DataUtils.ConvertValue<DateTime?>(reader["StartDate"]);
			this._EndDate = DataUtils.ConvertValue<DateTime?>(reader["EndDate"]);
			this._IsEnabled = DataUtils.ConvertValue<int?>(reader["IsEnabled"]);
			this._CreateUser = DataUtils.ConvertValue<int?>(reader["CreateUser"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime?>(reader["CreateTime"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._Title = DataUtils.ConvertValue<string>(row["Title"]);
			this._Summary = DataUtils.ConvertValue<string>(row["Summary"]);
			this._Type = DataUtils.ConvertValue<int?>(row["Type"]);
			this._MaxSels = DataUtils.ConvertValue<int?>(row["MaxSels"]);
			this._Total = DataUtils.ConvertValue<int?>(row["Total"]);
			this._StartDate = DataUtils.ConvertValue<DateTime?>(row["StartDate"]);
			this._EndDate = DataUtils.ConvertValue<DateTime?>(row["EndDate"]);
			this._IsEnabled = DataUtils.ConvertValue<int?>(row["IsEnabled"]);
			this._CreateUser = DataUtils.ConvertValue<int?>(row["CreateUser"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime?>(row["CreateTime"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsVote");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsVote","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","cmsVote","Title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Summary = new Field("Summary","cmsVote","Summary");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type","cmsVote","Type");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MaxSels = new Field("MaxSels","cmsVote","MaxSels");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Total = new Field("Total","cmsVote","Total");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StartDate = new Field("StartDate","cmsVote","StartDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EndDate = new Field("EndDate","cmsVote","EndDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsEnabled = new Field("IsEnabled","cmsVote","IsEnabled");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateUser = new Field("CreateUser","cmsVote","CreateUser");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","cmsVote","CreateTime");
		}
		#endregion


	}
}

