//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5444
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsVoteItemResult 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsVoteItemResult : Entity 
	{
		public cmsVoteItemResult():base("cmsVoteItemResult") {}

		#region Model
		private long _Id;
		private string _ResultId;
		private long _VoteId;
		private long _VoteItemId;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ResultId
		{
			get{ return _ResultId; }
			set
			{
				this.OnPropertyValueChange(_.ResultId,_ResultId,value);
				this._ResultId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long VoteId
		{
			get{ return _VoteId; }
			set
			{
				this.OnPropertyValueChange(_.VoteId,_VoteId,value);
				this._VoteId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long VoteItemId
		{
			get{ return _VoteItemId; }
			set
			{
				this.OnPropertyValueChange(_.VoteItemId,_VoteItemId,value);
				this._VoteItemId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ResultId,
				_.VoteId,
				_.VoteItemId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ResultId,
				this._VoteId,
				this._VoteItemId};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._ResultId = DataUtils.ConvertValue<string>(reader["ResultId"]);
			this._VoteId = DataUtils.ConvertValue<long>(reader["VoteId"]);
			this._VoteItemId = DataUtils.ConvertValue<long>(reader["VoteItemId"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._ResultId = DataUtils.ConvertValue<string>(row["ResultId"]);
			this._VoteId = DataUtils.ConvertValue<long>(row["VoteId"]);
			this._VoteItemId = DataUtils.ConvertValue<long>(row["VoteItemId"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsVoteItemResult");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsVoteItemResult","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ResultId = new Field("ResultId","cmsVoteItemResult","ResultId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VoteId = new Field("VoteId","cmsVoteItemResult","VoteId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VoteItemId = new Field("VoteItemId","cmsVoteItemResult","VoteItemId");
		}
		#endregion


	}
}

