//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5444
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Hxj.Data;
using Hxj.Data.Common;

namespace entCMS.Models
{

	/// <summary>
	/// 实体类cmsVoteItem 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class cmsVoteItem : Entity 
	{
		public cmsVoteItem():base("cmsVoteItem") {}

		#region Model
		private long _Id;
		private long _VoteId;
		private string _Title;
		private string _Summary;
		private string _ImgUrl;
		private int? _Result;
		private int? _OrderNo;
		/// <summary>
		/// 
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public long VoteId
		{
			get{ return _VoteId; }
			set
			{
				this.OnPropertyValueChange(_.VoteId,_VoteId,value);
				this._VoteId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Summary
		{
			get{ return _Summary; }
			set
			{
				this.OnPropertyValueChange(_.Summary,_Summary,value);
				this._Summary=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ImgUrl
		{
			get{ return _ImgUrl; }
			set
			{
				this.OnPropertyValueChange(_.ImgUrl,_ImgUrl,value);
				this._ImgUrl=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Result
		{
			get{ return _Result; }
			set
			{
				this.OnPropertyValueChange(_.Result,_Result,value);
				this._Result=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? OrderNo
		{
			get{ return _OrderNo; }
			set
			{
				this.OnPropertyValueChange(_.OrderNo,_OrderNo,value);
				this._OrderNo=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.VoteId,
				_.Title,
				_.Summary,
				_.ImgUrl,
				_.Result,
				_.OrderNo};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._VoteId,
				this._Title,
				this._Summary,
				this._ImgUrl,
				this._Result,
				this._OrderNo};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Id = DataUtils.ConvertValue<long>(reader["Id"]);
			this._VoteId = DataUtils.ConvertValue<long>(reader["VoteId"]);
			this._Title = DataUtils.ConvertValue<string>(reader["Title"]);
			this._Summary = DataUtils.ConvertValue<string>(reader["Summary"]);
			this._ImgUrl = DataUtils.ConvertValue<string>(reader["ImgUrl"]);
			this._Result = DataUtils.ConvertValue<int?>(reader["Result"]);
			this._OrderNo = DataUtils.ConvertValue<int?>(reader["OrderNo"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Id = DataUtils.ConvertValue<long>(row["Id"]);
			this._VoteId = DataUtils.ConvertValue<long>(row["VoteId"]);
			this._Title = DataUtils.ConvertValue<string>(row["Title"]);
			this._Summary = DataUtils.ConvertValue<string>(row["Summary"]);
			this._ImgUrl = DataUtils.ConvertValue<string>(row["ImgUrl"]);
			this._Result = DataUtils.ConvertValue<int?>(row["Result"]);
			this._OrderNo = DataUtils.ConvertValue<int?>(row["OrderNo"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cmsVoteItem");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","cmsVoteItem","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VoteId = new Field("VoteId","cmsVoteItem","VoteId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","cmsVoteItem","Title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Summary = new Field("Summary","cmsVoteItem","Summary");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ImgUrl = new Field("ImgUrl","cmsVoteItem","ImgUrl");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Result = new Field("Result","cmsVoteItem","Result");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OrderNo = new Field("OrderNo","cmsVoteItem","OrderNo");
		}
		#endregion


	}
}

